# SPDX-FileCopyrightText: Alice Frosi <afrosi@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: v1
kind: Service
metadata:
  name: ak-register-forward
  namespace: <NAMESPACE>
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 31002
    port: 8001
  selector:
    app: attestation-key-register
